### ISSUE TITLE
Examples http://examples.nextrtc.org/videochat/ is not working

### ISSUE THREAD

**Issue by deepakbandelach** [mslosarz/nextrtc-example-videochat#6]
I just checked http://examples.nextrtc.org/videochat/ the example is not working 

it says 502 bad gateway.

Can you please address this issue?

**Comment by mslosarz** [comment]
It doesn't work because I'm waiting for SSL certificate (so tomcat with
example is turned off).
New Chrome (I suspect that FF too) requires https protocol when you want to
use WebRTC. So util I don't have certificate examples won't work.
You can run this example locally (because at localhost it will work without
https)

2016-02-11 10:18 GMT+01:00 deepakbandelach notifications@github.com:

> Reopened #6
> https://github.com/mslosarz/nextrtc-example-videochat/issues/6.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mslosarz/nextrtc-example-videochat/issues/6#event-546898378
> .

## 

Marcin Ślósarz

**Comment by mslosarz** [comment]
Example back to work now
